#ifndef LIBSIDPLAYFP_VERSION_H
#define LIBSIDPLAYFP_VERSION_H

#ifndef SIDPLAYFP_H
#  error Do not include directly.
#endif



#define LIBSIDPLAYFP_VERSION_MAJ 2//@LIB_MAJOR@
#define LIBSIDPLAYFP_VERSION_MIN 3//@LIB_MINOR@
#define LIBSIDPLAYFP_VERSION_LEV 1//@LIB_LEVEL@

#endif
